[package]
name = "rustmius"
version = "0.2.0"
edition = "2024"

[dependencies]
libadwaita = { version = "0.8", features = ["v1_7"] }
gtk4 = "0.10.0"
dirs = "6.0"
base64 = "0.22"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.8", features = ["v4", "fast-rng", "serde"] }
