name: Manual AUR Publish

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      publish_rustmius:
        description: 'Publish rustmius (source package)'
        required: false
        type: boolean
        default: false
      publish_rustmius_bin:
        description: 'Publish rustmius-bin (binary package)'
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: AUR Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Publish AUR package (rustmius)
        if: ${{ github.event.inputs.publish_rustmius == 'true' }}
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: rustmius
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519

      - name: Publish AUR package (rustmius-bin)
        if: ${{ github.event.inputs.publish_rustmius_bin == 'true' }}
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: rustmius-bin
          pkgbuild: ./PKGBUILD-BIN
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519