name: Manual AUR Publish

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Install git
        run: pacman -Syu --noconfirm git

      - name: Check if PKGBUILD changed
        id: check-rustmius
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^PKGBUILD$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if PKGBUILD-BIN changed
        id: check-rustmius-bin
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^PKGBUILD-BIN$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish AUR package (rustmius)
        if: steps.check-rustmius.outputs.changed == 'true'
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: rustmius
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519

      - name: Publish AUR package (rustmius-bin)
        if: steps.check-rustmius-bin.outputs.changed == 'true'
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: rustmius-bin
          pkgbuild: ./PKGBUILD-BIN
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
